sabueso.\_private\_tools.exceptions.BadCallError
================================================

.. currentmodule:: sabueso._private_tools.exceptions

.. autoexception:: BadCallError